// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_hard_stage_2 = "CgkIs57ggsUUEAIQCg"; // <GPGSID>
        public const string leaderboard_easy_stage_5 = "CgkIs57ggsUUEAIQCA"; // <GPGSID>
        public const string leaderboard_easy_stage_2 = "CgkIs57ggsUUEAIQBQ"; // <GPGSID>
        public const string achievement_game_master = "CgkIs57ggsUUEAIQDg"; // <GPGSID>
        public const string leaderboard_easy_stage_1 = "CgkIs57ggsUUEAIQBA"; // <GPGSID>
        public const string leaderboard_hard_stage_5 = "CgkIs57ggsUUEAIQDQ"; // <GPGSID>
        public const string achievement_master_of_master = "CgkIs57ggsUUEAIQDw"; // <GPGSID>
        public const string leaderboard_loginleaderboard = "CgkIs57ggsUUEAIQAQ"; // <GPGSID>
        public const string leaderboard_hard_stage_3 = "CgkIs57ggsUUEAIQCw"; // <GPGSID>
        public const string leaderboard_easy_stage_4 = "CgkIs57ggsUUEAIQBw"; // <GPGSID>
        public const string leaderboard_easy_stage_3 = "CgkIs57ggsUUEAIQBg"; // <GPGSID>
        public const string leaderboard_hard_stage_1 = "CgkIs57ggsUUEAIQCQ"; // <GPGSID>
        public const string leaderboard_hard_stage_4 = "CgkIs57ggsUUEAIQDA"; // <GPGSID>

}

